name: My Action
description: description

runs:
  using: "composite"
  steps:
    - name: Step 1
      run: echo "This is step 1 of the composite action"
    - name: Step 2
      run: |
        echo "Step 2a - build docker iamge only"
        echo "github.ref: ${{ github.ref }}"
        echo "github.head_ref: ${{ github.head_ref }}"
        echo "github.base_ref: ${{ github.base_ref }}"
        echo "github.event_name: ${{ github.event_name }}"
        echo "github.event.action: ${{ github.event.action }}"
        echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"