
name: Aurora API CI/CD pipeline

on:
  push:
    branches:
      - release
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types:
      - opened
      - closed

jobs: 
  the_first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Do not run with the tag trigger
    if: startsWith(github.ref, 'refs/tags/') == false
    steps: 
      - name: build and test
        run: |
            echo "github.ref: ${{ github.ref }}"
            echo "github.head_ref: ${{ github.head_ref }}"
            echo "github.base_ref: ${{ github.base_ref }}"
            echo "github.event_name: ${{ github.event_name }}"
            echo "github.event.action: ${{ github.event.action }}"
            echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"

  build_image_and_push_dev:
    needs: the_first_job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Run only the PR is to master branch
    if: github.base_ref == 'refs/heads/master'
    steps: 
      - name: build and push - dev
        run: |
            echo "github.ref: ${{ github.ref }}"
            echo "github.head_ref: ${{ github.head_ref }}"
            echo "github.base_ref: ${{ github.base_ref }}"
            echo "github.event_name: ${{ github.event_name }}"
            echo "github.event.action: ${{ github.event.action }}"
            echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"
        
  build_image_and_push_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    # Run only with the tag trigger
    if: startsWith(github.ref, 'refs/tags/')
    steps: 
    - name: build and push - prod
      run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.action: ${{ github.event.action }}"
          echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"
  
        