
name: Aurora API CI/CD pipeline

on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types:
      - opened
      - closed

jobs: 
  build_image_and_push_dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps: 
      - name: Extract version from tag - dev
        run: |
            echo "github.ref: ${{ github.ref }}"
            echo "github.head_ref: ${{ github.head_ref }}"
            echo "github.base_ref: ${{ github.base_ref }}"
            echo "github.event_name: ${{ github.event_name }}"
            echo "github.event.action: ${{ github.event.action }}"
            echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"
        
  build_image_and_push_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    if: startsWith(github.ref, 'refs/tags/')
    steps: 
    - name: Extract version from tag - prod
      run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.action: ${{ github.event.action }}"
          echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"
  
        