
name: Aurora API CI/CD pipeline

on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types:
      - opened
      - closed
      - synchronize
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'
      - 'docs/**/*'
      - 'scripts/**/*'

jobs: 
  test_steps_with_conditions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps: 
      - uses: actions/checkout@v2
      - name: Step 1 - Try composit
        uses: ./.github/actions/my-action
        # run: echo "This step always runs"

       # Do not run with the pr, which is not closed
      - name: Step 2a - build docker iamge only
        if: startsWith(github.ref, 'refs/pull/') && github.base_ref == 'master' && github.event.action != 'closed'
        run: |
            echo "Step 2a - build docker iamge only"
            echo "secrets.PAT: ${{ secrets.PAT }}"
            echo "github.ref: ${{ github.ref }}"
            echo "github.head_ref: ${{ github.head_ref }}"
            echo "github.base_ref: ${{ github.base_ref }}"
            echo "github.event_name: ${{ github.event_name }}"
            echo "github.event.action: ${{ github.event.action }}"
            echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"
      # Run only the PR is to master branch and merged
      - name: Step 2b - build and push - dev
        if: github.base_ref == 'master' && github.event.pull_request.merged == true
        run: |
            echo "Step 2b - build and push - dev"
            echo "github.ref: ${{ github.ref }}"
            echo "github.head_ref: ${{ github.head_ref }}"
            echo "github.base_ref: ${{ github.base_ref }}"
            echo "github.event_name: ${{ github.event_name }}"
            echo "github.event.action: ${{ github.event.action }}"
            echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"
      # Run only with the tag trigger
      - name: Step 2c - build and push - prod
        if: startsWith(github.ref, 'refs/tags/')
        run: |
            echo "Step 2c - build and push - prod"
            echo "github.ref: ${{ github.ref }}"
            echo "github.head_ref: ${{ github.head_ref }}"
            echo "github.base_ref: ${{ github.base_ref }}"
            echo "github.event_name: ${{ github.event_name }}"
            echo "github.event.action: ${{ github.event.action }}"
            echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"
      - name: Step 3
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: heons/test-cicd-dispatch
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

  docker_build_dev_pr_to_master_opened_only:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Do not run with the pr, which is not closed
    if: startsWith(github.ref, 'refs/pull/') && github.base_ref == 'master' && github.event.action != 'closed'
    steps: 
      - name: build docker iamge only
        run: |
            echo "github.ref: ${{ github.ref }}"
            echo "github.head_ref: ${{ github.head_ref }}"
            echo "github.base_ref: ${{ github.base_ref }}"
            echo "github.event_name: ${{ github.event_name }}"
            echo "github.event.action: ${{ github.event.action }}"
            echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"

  docker_build_and_push_dev_pr_to_master_merged_only:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Run only the PR is to master branch and merged
    if: github.base_ref == 'master' && github.event.pull_request.merged == true
    steps: 
      - name: build and push - dev
        run: |
            echo "github.ref: ${{ github.ref }}"
            echo "github.head_ref: ${{ github.head_ref }}"
            echo "github.base_ref: ${{ github.base_ref }}"
            echo "github.event_name: ${{ github.event_name }}"
            echo "github.event.action: ${{ github.event.action }}"
            echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"
        
  docker_build_and_push_prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    # Run only with the tag trigger
    if: startsWith(github.ref, 'refs/tags/')
    steps: 
    - name: build and push - prod
      run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.event.action: ${{ github.event.action }}"
          echo "github.event.pull_request.merged : ${{ github.event.pull_request.merged  }}"
  
        