name: Auto PR from master to release

on:
  workflow_dispatch:

jobs:
  createPR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          destination_branch: "release"
          pr_title: "Master to release - should come from input"
          # pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
          # pr_reviewer: "paigen11"
          pr_draft: false
      - name: Enable auto-merge
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge